"""BayesIQ Dashboard — Generated by BayesIQ Data Audit Kit."""

import json
import os
import re

import pandas as pd
import plotly.express as px
import streamlit as st

st.set_page_config(page_title="BayesIQ Dashboard", layout="wide")


def _fmt_period(series):
    """Shorten period strings for compact x-axis labels."""
    def _shorten(s):
        # Weekly: "2025-12-01/2025-12-07" → "Dec 1"
        if "/" in s:
            s = s.split("/")[0]
        # Monthly: "2025-12" → "Dec '25"
        parts = s.split("-")
        if len(parts) >= 2:
            import calendar
            try:
                mon = calendar.month_abbr[int(parts[1])]
                if len(parts) == 2:
                    return f"{mon} '{parts[0][2:]}"
                return f"{mon} {int(parts[2])}"
            except (ValueError, IndexError):
                pass
        return s
    return series.map(_shorten)


def _humanize_label(col_name):
    """Convert snake_case column name to human-readable axis label."""
    return col_name.replace("_", " ").title()


def _polish_fig(fig, y_col, show_legend=True):
    """Apply consistent axis and legend polish to a Plotly figure."""
    fig.update_yaxes(title_text=_humanize_label(y_col))
    fig.update_xaxes(title_text="", tickangle=-30)
    if not show_legend:
        fig.update_layout(showlegend=False)

@st.cache_data
def load_data(path):
    """Load and clean the dataset from a file path."""
    if path.endswith('.parquet'):
        df = pd.read_parquet(path)
    else:
        df = pd.read_csv(path)

    if "transaction_date" in df.columns:
        df["transaction_date"] = pd.to_datetime(df["transaction_date"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["store_id", "department", "brand", "channel", "upc", "sku", "product_name", "quantity", "units_sold", "units_received", "revenue", "cost", "margin", "price", "discount", "return_flag", "exchange_flag", "transaction_date", "sell_through_flag", "premium_flag", "transaction_flag"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


@st.cache_data
def load_uploaded(file):
    """Load and clean a dataset from an uploaded file."""
    if file.name.endswith('.parquet'):
        df = pd.read_parquet(file)
    else:
        df = pd.read_csv(file)

    if "transaction_date" in df.columns:
        df["transaction_date"] = pd.to_datetime(df["transaction_date"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["store_id", "department", "brand", "channel", "upc", "sku", "product_name", "quantity", "units_sold", "units_received", "revenue", "cost", "margin", "price", "discount", "return_flag", "exchange_flag", "transaction_date", "sell_through_flag", "premium_flag", "transaction_flag"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


def main():
    st.title("BayesIQ Data Dashboard")

    st.sidebar.header("Data Source")
    uploaded_file = st.sidebar.file_uploader(
        "Upload CSV or Parquet",
        type=["csv", "parquet", "pq"],
        help="Drag and drop a file here, or click to browse."
    )
    default_path = "data/raw_month_3.csv"
    data_path = st.sidebar.text_input("Or enter file path", value=default_path)

    # Load from upload or path
    df = None
    if uploaded_file is not None:
        try:
            df = load_uploaded(uploaded_file)
        except Exception as e:
            st.error(f"Could not load uploaded file: {e}")
            return
    elif data_path:
        try:
            df = load_data(data_path)
        except Exception as e:
            st.error(f"Could not load dataset: {e}")
            return
    else:
        st.info("Upload a file or enter a dataset path in the sidebar to get started.")
        return

    # Auto-detect period: weekly for short datasets, monthly otherwise
    _period = "M"
    if "transaction_date" in df.columns:
        _ts_range = df["transaction_date"].max() - df["transaction_date"].min()
        if _ts_range.days <= 45:
            _period = "W"

    # --- Column Role Wizard ---
    roles_file = os.path.join(os.path.dirname(__file__), "column_roles_resolved.json")
    saved_roles = {}
    if os.path.exists(roles_file):
        with open(roles_file) as _f:
            saved_roles = json.load(_f)

    ambiguous_cols = ["store_id"]
    unresolved = [c for c in ambiguous_cols if c not in saved_roles]

    if unresolved:
        st.info("Some columns contain embedded numbers (e.g. \"5 Pack\", \"8 MILLIGRAM\"). Tell us how to use them.")
        with st.expander("Configure column roles", expanded=True):
            wizard_roles = {}
            st.markdown("**store_id** — e.g. STORE-001, STORE-002, STORE-003")
            store_id_role = st.radio(
                "Role for store_id",
                ['Use as filter (categorical)', 'Use as ordered axis (sort by number)', 'Use as numeric multiplier', 'Ignore this column'],
                index=0,
                key="wizard_store_id",
                horizontal=True,
            )
            wizard_roles["store_id"] = {"role": store_id_role}
            if "multiplier" in store_id_role.lower():
                store_id_target = st.selectbox(
                    "Multiply against",
                    ["quantity", "units_sold", "units_received", "revenue", "cost", "margin", "price", "discount", "return_flag", "exchange_flag", "sell_through_flag", "premium_flag", "transaction_flag"],
                    index=0,
                    key="wizard_store_id_target",
                )
                wizard_roles["store_id"]["multiply_against"] = store_id_target

            if st.button("Save column roles", type="primary"):
                saved_roles.update(wizard_roles)
                with open(roles_file, 'w') as _f:
                    json.dump(saved_roles, _f, indent=2)
                st.success("Column roles saved. Reloading...")
                st.rerun()

    # Apply resolved column roles
    for col_name, role_info in saved_roles.items():
        if col_name not in df.columns:
            continue
        role_str = role_info.get("role", "")
        if "multiplier" in role_str.lower():
            target = role_info.get("multiply_against")
            if target and target in df.columns:
                nums = df[col_name].astype(str).str.extract(r"(\d+(?:\.\d+)?)", expand=False).astype(float)
                derived_name = role_info.get("derived_metric_name", f"{target}_x_{col_name}")
                df[derived_name] = df[target] * nums
        elif "ordered" in role_str.lower() or "ordinal" in role_str.lower():
            sort_order = df[col_name].drop_duplicates().to_frame()
            sort_order["_sort"] = sort_order[col_name].astype(str).str.extract(r"(\d+(?:\.\d+)?)", expand=False).astype(float)
            sort_order = sort_order.sort_values("_sort")[col_name].tolist()
            df[col_name] = pd.Categorical(df[col_name], categories=sort_order, ordered=True)

    # --- Sidebar Filters ---
    st.sidebar.header("Filters")

    if "transaction_date" in df.columns:
        min_date = df["transaction_date"].min().date()
        max_date = df["transaction_date"].max().date()
        date_range = st.sidebar.date_input(
            "Date Range",
            value=(min_date, max_date),
            min_value=min_date,
            max_value=max_date,
        )
        if len(date_range) == 2:
            df = df[(df["transaction_date"].dt.date >= date_range[0]) &
                    (df["transaction_date"].dt.date <= date_range[1])]

    if "department" in df.columns:
        department_opts = sorted(df["department"].dropna().unique().tolist())
        department_sel = st.sidebar.multiselect(
            "department",
            options=department_opts,
            default=department_opts,
        )
        df = df[df["department"].isin(department_sel)]

    if "brand" in df.columns:
        brand_opts = sorted(df["brand"].dropna().unique().tolist())
        brand_sel = st.sidebar.multiselect(
            "brand",
            options=brand_opts,
            default=brand_opts,
        )
        df = df[df["brand"].isin(brand_sel)]

    if "channel" in df.columns:
        channel_opts = sorted(df["channel"].dropna().unique().tolist())
        channel_sel = st.sidebar.multiselect(
            "channel",
            options=channel_opts,
            default=channel_opts,
        )
        df = df[df["channel"].isin(channel_sel)]

    if "quantity" in df.columns:
        quantity_opts = sorted(df["quantity"].dropna().unique().tolist())
        quantity_sel = st.sidebar.multiselect(
            "quantity",
            options=quantity_opts,
            default=quantity_opts,
        )
        df = df[df["quantity"].isin(quantity_sel)]

    if "units_sold" in df.columns:
        units_sold_opts = sorted(df["units_sold"].dropna().unique().tolist())
        units_sold_sel = st.sidebar.multiselect(
            "units_sold",
            options=units_sold_opts,
            default=units_sold_opts,
        )
        df = df[df["units_sold"].isin(units_sold_sel)]

    if "units_received" in df.columns:
        units_received_opts = sorted(df["units_received"].dropna().unique().tolist())
        units_received_sel = st.sidebar.multiselect(
            "units_received",
            options=units_received_opts,
            default=units_received_opts,
        )
        df = df[df["units_received"].isin(units_received_sel)]

    if "return_flag" in df.columns:
        return_flag_opts = sorted(df["return_flag"].dropna().unique().tolist())
        return_flag_sel = st.sidebar.multiselect(
            "return_flag",
            options=return_flag_opts,
            default=return_flag_opts,
        )
        df = df[df["return_flag"].isin(return_flag_sel)]

    if "exchange_flag" in df.columns:
        exchange_flag_opts = sorted(df["exchange_flag"].dropna().unique().tolist())
        exchange_flag_sel = st.sidebar.multiselect(
            "exchange_flag",
            options=exchange_flag_opts,
            default=exchange_flag_opts,
        )
        df = df[df["exchange_flag"].isin(exchange_flag_sel)]

    if "sell_through_flag" in df.columns:
        sell_through_flag_opts = sorted(df["sell_through_flag"].dropna().unique().tolist())
        sell_through_flag_sel = st.sidebar.multiselect(
            "sell_through_flag",
            options=sell_through_flag_opts,
            default=sell_through_flag_opts,
        )
        df = df[df["sell_through_flag"].isin(sell_through_flag_sel)]

    if "premium_flag" in df.columns:
        premium_flag_opts = sorted(df["premium_flag"].dropna().unique().tolist())
        premium_flag_sel = st.sidebar.multiselect(
            "premium_flag",
            options=premium_flag_opts,
            default=premium_flag_opts,
        )
        df = df[df["premium_flag"].isin(premium_flag_sel)]

    st.sidebar.metric("Rows (filtered)", f"{len(df):,}")
    deduped = df.attrs.get("rows_deduped", 0)
    if deduped:
        st.sidebar.metric("Rows deduped", f"{deduped:,}")

    tabs = st.tabs(["Metrics", "Data Quality", "Raw Data"])

    with tabs[0]:
        st.header("Business Metrics")

        _compact = dict(height=260, margin=dict(l=40, r=20, t=40, b=30),
                        title_font_size=13,
                        legend=dict(orientation="h", y=-0.25, font=dict(size=10)))

        _dim_options = ["Topline", "department", "channel", "brand"]
        _sel_dim = st.radio("Dimension", _dim_options, index=0, horizontal=True, key="dim_radio")
        _dim_col = None if _sel_dim == "Topline" else _sel_dim
        _legend_shown = False

        # Helper for ratio metrics in this vertical
        def _ratio_chart(num_df, den_df, metric_name, title):
            nonlocal _legend_shown
            if _dim_col and _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["transaction_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["transaction_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, metric_name]
                ratio_dim["period"] = _fmt_period(ratio_dim["period"].astype(str))
                if ratio_dim.empty:
                    st.info(f"No data for {title}.")
                else:
                    fig = px.line(ratio_dim, x="period", y=metric_name, color=_dim_col, title=title, markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, metric_name, show_legend=not _legend_shown)
                    _legend_shown = True
                    st.plotly_chart(fig, use_container_width=True)
            else:
                den_grouped = den_df.groupby(den_df["transaction_date"].dt.to_period(_period)).size()
                num_grouped = num_df.groupby(num_df["transaction_date"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
                ratio_result = (num_grouped / den_grouped).fillna(0).reset_index()
                ratio_result.columns = ["period", metric_name]
                ratio_result["period"] = _fmt_period(ratio_result["period"].astype(str))
                if ratio_result.empty:
                    st.info(f"No data for {title}.")
                else:
                    fig = px.line(ratio_result, x="period", y=metric_name, title=title, markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, metric_name)
                    st.plotly_chart(fig, use_container_width=True)

        # --- Row 1 ---
        r1c1, r1c2, r1c3 = st.columns(3)

        with r1c1:
            _ratio_chart(df[(df["return_flag"] == 1)], df[(df["transaction_flag"] == 1)], "return_rate", "Return Rate (%)")

        with r1c2:
            _ratio_chart(df[(df["sell_through_flag"] == 1)], df[(df["transaction_flag"] == 1)], "sell_through", "Sell Through (%)")

        with r1c3:
            _ratio_chart(df[(df["premium_flag"] == 1)], df[(df["transaction_flag"] == 1)], "premium_mix", "Premium Mix (%)")

        # --- Row 2 ---
        r2c1, r2c2, r2c3 = st.columns(3)

        with r2c1:
            metric_df = df
            if "revenue" not in metric_df.columns:
                st.warning("Column \"revenue\" not found — skipping Store Performance.")
            else:
                if _dim_col and _dim_col in metric_df.columns:
                    grouped = metric_df.groupby([metric_df["transaction_date"].dt.to_period(_period), _dim_col])["revenue"].sum().reset_index()
                    grouped.columns = ["period", _dim_col, "store_performance"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="store_performance", color=_dim_col, title="Store Performance ($)", barmode="group")
                else:
                    grouped = metric_df.groupby(metric_df["transaction_date"].dt.to_period(_period))["revenue"].sum().reset_index()
                    grouped.columns = ["period", "store_performance"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="store_performance", title="Store Performance ($)")
                fig.update_layout(**_compact)
                _polish_fig(fig, "store_performance", show_legend=not _legend_shown and _dim_col is not None)
                if _dim_col: _legend_shown = True
                st.plotly_chart(fig, use_container_width=True)

        with r2c2:
            metric_df = df
            if "margin" not in metric_df.columns:
                st.warning("Column \"margin\" not found — skipping Revenue Integrity.")
            else:
                if _dim_col and _dim_col in metric_df.columns:
                    grouped = metric_df.groupby([metric_df["transaction_date"].dt.to_period(_period), _dim_col])["margin"].sum().reset_index()
                    grouped.columns = ["period", _dim_col, "revenue_integrity"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="revenue_integrity", color=_dim_col, title="Revenue Integrity ($)", barmode="group")
                else:
                    grouped = metric_df.groupby(metric_df["transaction_date"].dt.to_period(_period))["margin"].sum().reset_index()
                    grouped.columns = ["period", "revenue_integrity"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="revenue_integrity", title="Revenue Integrity ($)")
                fig.update_layout(**_compact)
                _polish_fig(fig, "revenue_integrity", show_legend=not _legend_shown and _dim_col is not None)
                if _dim_col: _legend_shown = True
                st.plotly_chart(fig, use_container_width=True)

        with r2c3:
            st.markdown("##### KPI Summary")
            st.markdown(f"**Total Rows:** {len(df):,}")
            if "transaction_date" in df.columns:
                _min = df["transaction_date"].min().strftime("%Y-%m-%d")
                _max = df["transaction_date"].max().strftime("%Y-%m-%d")
                st.markdown(f"**Date Range:** {_min} to {_max}")
            if "revenue" in df.columns:
                _total_rev = df["revenue"].sum()
                st.markdown(f"**Total Revenue:** ${_total_rev:,.0f}")

    with tabs[1]:
        st.header("Data Quality Summary")
        st.metric("Total Issues Found", 2)

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Critical", 0)
        col2.metric("High", 1)
        col3.metric("Medium", 1)
        col4.metric("Low", 0)

        st.info("This dashboard applies automatic cleaning: value canonicalization and near-duplicate deduplication. The issues below were detected in the raw data before cleaning.")

        st.subheader("Findings")
        st.markdown("**1. [HIGH]** Near-duplicate rows detected (128 rows)")
        st.markdown("**2. [MEDIUM]** sell_through misreported for 2025-12 (off by +8.6%) (1 rows)")

    with tabs[2]:
        st.header("Raw Data")
        st.dataframe(df.head(1000), use_container_width=True)


if __name__ == "__main__":
    main()
